### ISSUE TITLE
After falling off map and respawning, timer does not reset

### ISSUE THREAD

**Issue by chilidawg22** [FIS-game-development-club/2018#99] opened 2018-04-16 13:50 UTC

**Comment by mvpwizard** [comment] 2018-04-16 14:11
I think that is by design. If you die while playing the level you will get a worse score.

**Comment by karsten2004** [comment] 2018-04-16 15:53
that is by design

**Comment by karsten2004** [comment] 2018-04-16 15:54
it is supposed to be so you get a worse score after dying

**Comment by karsten2004** [comment] 2018-04-16 15:54
I will close this issue now

**Closed as completed** 2018-04-16 15:54 UTC
Labels: Programming, Notification
